### ISSUE TITLE
Support for Ambassador Pattern and KWIC

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway.docker#8]
# Description

 - The ambassador pattern is described [here](https://docs.docker.com/engine/articles/ambassador_pattern_linking/). 
 - KWIC solves a similar issue and is described [here](http://kaazing.com/kwic/)

It allows ambassador containers to wire up containers so that changes to networking and network configuration is isolated to the ambassador containers, and not the core application containers.

There are other awesome prepackaged docker containers that have support for the ambassador pattern, specifically
svendowideit/ambassador (referenced in the docker docs) and sojournlabs/ambassador (which allows encryption of network).

The kaazing-gateway docker image could provide both the advantages of above but also would enable the following

#### 1. Connecting separate networks and container environments locally, or across the web with websocket connection.  
  - provides several advantages to tcp/tls [1](http://stackoverflow.com/questions/2681267/what-is-the-fundamental-difference-between-websockets-and-pure-tcp), [2](http://blog.kaazing.com/2012/02/28/html5-websocket-security-is-strong/).
  - Most notably, only one standardize ports are exposed (80 or 443)

   ```
   (consumer) --> (ambassador) --- network (tcp over wss) ---> (ambassador) --> (server) 
   ```

####  2. Multiplexing tcp containers onto a single ws url, thereby multiplexing multiple tcp streams over a single exposed port.

   ```
   (consumer 1) -->                                                           --> (server 1) 
   (consumer 2) --> (ambassador) --- network (tcp over wss) ---> (ambassador) --> (server 2) 
   (consumer 3) -->                                                           --> (server 3) 
   ```

#### 4. With enterprise kaazing gateway reverse connectivity would be enabled 

   ```
   (consumer 1) -->                                                           --> (server 1) 
   (consumer 2) --> (ambassador) <--- network (tcp over wss) --- (ambassador) --> (server 2) 
   (consumer 3) -->                                                           --> (server 3) 
   ```
#### 5. Integrated support for http proxying

   ```
   (consumer 1) -->                                                                   --> (server 1) 
   (consumer 2) --> (ambassador) --- network (tcp or http over wss) ---> (ambassador) --> (server 2) 
   (consumer 3) -->                                                                   --> (server 3) 
   ```

which allows 
  - http auth at ambassador (either) for the consumer.  Meaning this is a single point of configuration
  - etc

# Proposed Implementation / Process

- [x] Working demo, done and available at https://github.com/dpwspoon/gateway.docker/tree/feature/support-for-ambassador/ambassador-pattern/working-sample
- [ ] Parameterize implementation to allow endpoints, keystore/truststore, and multiple services to be parameterized via command line arguments (design to be discussed
- [ ] Update repo, readme, and official kaazing-gateway docker image with scripts. 
- [ ] Update docker official image repos to pull in new image
- [ ] Create demo on deployments using compose for one side and compose for anther side.  Design to be discussed, but could use compose parameters to show app progressing from qa to production

**Comment by amalc** [comment]
Could non Dev environments could inject OS variable names in DB names etc?

**Comment by dpwspoon** [comment]
Yes, they should be able to passed in at runtime, or with [variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution:91de898b5f5cdb090642a917d3dedf68) when using compose

**Comment by dpwspoon** [comment]
Possible commands maybe

```
docker kaazing-gateway generate-ambassador-keys.  
docker kaazing-gateway start-server-ambassador -connect-to echo.service.ip:9000
docker kaazing-gateway start-client-ambassador connect-to ip.of.server.ambassador
```

**Comment by dpwspoon** [comment]
@arnaldoroldan,  Thanks for the demo on where you are at.  It's looking pretty good.   Feedback and possibilities as discussed on the call are.

1. The configuration really needs to be at runtime and not connecting to the container.  Additionally, I don't think it is ideal to require them to build the image.  We want them to pull from something like [kaazing-gateway](https://hub.docker.com/_/kaazing-gateway/) and only run a single run command to get started.  (Note: pulling is done just once.

2. Keystore and truststore.  If they aren't present I think we should throw a warning a proceed with un secure

3. I think keystore and truststore are a special case where you will want to generate them once and then move them around as needed, meaning we don't need to generate them at runtime of ambassador-server and ambassador-client.  I'd be open to do them at runtime if we could do it securely and simply, but I don't know of a good way to do that.  Though I expect @amalc to strongly prefer the latter

4.  We talked about a trick to get the configuration over from the server-ambassador over to the client-ambassador.  (Note: this does not include keystore/truststore, and would need to be done after the configuration).  What I noticed was that it seems the client-ambassador configuration can be derived from the server-ambassador, other then the ip address of the server ambassador. I think you could do this by binding the server ambassador to http://${hostname}:(same.port.as.websocket}/configuration-path with a directory service that serves the configuration.  Happy to go in more detail with you on this, but essentially the client-ambassador would need to connect to the directory service (perhaps using the local gateway as a proxy to do secure keystore truststore connection) and then restart the gateway with the new configuration.

**Comment by dpwspoon** [comment]
@amalc @arnaldoroldan 

The docker news letter today announced [new features to docker-compose](https://blog.docker.com/2016/02/compose-1-6/?mkt_tok=3RkMMJWWfF9wsRonuqTMZKXonjHpfsX57ewqWaG1lMI%2F0ER3fOvrPUfGjI4DScBkI%2BSLDwEYGJlv6SgFQ7LMMaZq1rgMXBk%3D) and show how it is suppose to work with overlay.  I haven't tried it out yet, and plan to tonight.  But it looks like we can fit in fairly well and show the power of our stuff with their own [demo](https://github.com/docker/example-voting-app). 

It looks like in it they have a front-tier network for apps and a back-tier network for db and workers.  The front-tier all have direct access to the back, with out permissions, encryption, or a way integrate with legacy backend networks that don't support the underlying overlay networks or SDNs.  I think once @arnaldoroldan gets the ambassador-kwik a little more finalized I might be able to rework the official docker demo to work in our stuff and show the advantages.

**Comment by dpwspoon** [comment]
@arnaldoroldan @amalc, one last thing on the design point of view.  I imagine the KWIC / ambassador pattern as being available on the same docker image as kaazing-gateway (which this repo deals with).   @arnaldoroldan I image that might affect your parameterization and scripting a little.  By default I think it should run gateway-start as defined above, but if something is passed in to specify ambassador then it should fall through to your code

**Comment by dpwspoon** [comment]
resolved in https://github.com/kaazing/gateway.docker/pull/9
